/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    categories: Category;
    tags: Tag;
    authors: Author;
    media: Media;
    users: User;
    sources: Source;
    'scraped-items': ScrapedItem;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'scraped-items': ScrapedItemsSelect<false> | ScrapedItemsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uz-Latn' | 'uz-Cyrl') | ('uz-Latn' | 'uz-Cyrl')[];
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'telegram-settings': TelegramSetting;
    'scraping-settings': ScrapingSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'telegram-settings': TelegramSettingsSelect<false> | TelegramSettingsSelect<true>;
    'scraping-settings': ScrapingSettingsSelect<false> | ScrapingSettingsSelect<true>;
  };
  locale: 'uz-Latn' | 'uz-Cyrl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'feed.poll': TaskFeedPoll;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      scrapeItem: WorkflowScrapeItem;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Saytda "Manba: …" blokida ko‘rsatiladi (TZ §2.3).
   */
  sources?:
    | {
        name?: string | null;
        url: string;
        scrapedItem?: (number | null) | ScrapedItem;
        id?: string | null;
      }[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  notesForEditor?: string | null;
  reviewNotes?:
    | {
        user?: (number | null) | User;
        createdAt?: string | null;
        note: string;
        id?: string | null;
      }[]
    | null;
  rejectReason?: string | null;
  telegram?:
    | {
        script: 'uz-Latn' | 'uz-Cyrl';
        messageId?: string | null;
        sentAt?: string | null;
        error?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * { title, excerpt, content, meta } — M1-03 transliteratsiyasi boshqaradi
   */
  cyrlLocked?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    focusKeyword?: string | null;
    noindex?: boolean | null;
  };
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  workflowStatus: 'draft' | 'in_progress' | 'review' | 'scheduled' | 'published' | 'rejected' | 'archived';
  category: number | Category;
  tags?: (number | Tag)[] | null;
  authors?: (number | Author)[] | null;
  assignee?: (number | null) | User;
  lockedUntil?: string | null;
  publishedAt?: string | null;
  /**
   * "Rejalashtirilgan" holatida shu vaqtda avtomatik chop etiladi
   */
  scheduledAt?: string | null;
  rewrittenBy?: ('human' | 'ai_agent') | null;
  /**
   * "AI agent" tanlanganda avtomatik yoqiladi
   */
  aiDisclosure?: boolean | null;
  isFeatured?: boolean | null;
  isBreaking?: boolean | null;
  telegramSkip?: boolean | null;
  /**
   * Lotin o‘zgargan, kirill qulflangan (M1-03)
   */
  cyrlStale?: boolean | null;
  readingTime?: number | null;
  views?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  license?: ('own' | 'press_kit' | 'unsplash' | 'pexels' | 'cc_by' | 'ai_generated' | 'other') | null;
  licenseUrl?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraped-items".
 */
export interface ScrapedItem {
  id: number;
  title?: string | null;
  source: number | Source;
  status: 'pending' | 'scraped' | 'drafted' | 'rejected' | 'duplicate' | 'error';
  url: string;
  canonicalUrl?: string | null;
  urlHash: string;
  author?: string | null;
  publishedAt?: string | null;
  language?: ('en' | 'ru') | null;
  excerpt?: string | null;
  extractedText?: string | null;
  imageUrls?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  sourceTags?: string[] | null;
  contentHash?: string | null;
  clusterId?: string | null;
  rawHtmlKey?: string | null;
  cleanHtmlKey?: string | null;
  fetchMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  score?: number | null;
  wordCount?: number | null;
  suggestedCategory?: (number | null) | Category;
  post?: (number | null) | Post;
  rejectReason?: string | null;
  handledBy?: (number | null) | User;
  handledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  homepageUrl: string;
  feeds?:
    | {
        url: string;
        feedCategory?: string | null;
        mapsTo?: (number | null) | Category;
        isActive?: boolean | null;
        lastPolledAt?: string | null;
        lastStatus?: number | null;
        lastNewItems?: number | null;
        etag?: string | null;
        lastModified?: string | null;
        lastError?: string | null;
        id?: string | null;
      }[]
    | null;
  language: 'en' | 'ru';
  fetchMode: 'rss_only' | 'rss_plus_page';
  priority?: number | null;
  pollIntervalMin?: number | null;
  rateLimitSec?: number | null;
  /**
   * { "content": "...", "title"?, "author"?, "publishedAt"?, "remove"?: [] }
   */
  selectors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  keywordRules?:
    | {
        keyword: string;
        category: number | Category;
        boost?: number | null;
        id?: string | null;
      }[]
    | null;
  tosNotes?: string | null;
  isActive?: boolean | null;
  robotsCheckedAt?: string | null;
  /**
   * Domen bo‘yicha rate limit (rateLimitSec) uchun
   */
  lastRequestAt?: string | null;
  /**
   * Oxirgi muvaffaqiyat/xato, ketma-ket xatolar soni
   */
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    focusKeyword?: string | null;
    noindex?: boolean | null;
  };
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  /**
   * HEX, masalan #52397F (design/brand/tokens.json → category.*.solid)
   */
  color?: string | null;
  order?: number | null;
  isInMenu?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  author?: (number | null) | Author;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  position?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  user?: (number | null) | User;
  isActive?: boolean | null;
  socials?:
    | {
        platform: 'telegram' | 'x' | 'linkedin' | 'github' | 'instagram' | 'youtube' | 'facebook' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Qidiruv va klassifikatsiya uchun muqobil yozilishlar (masalan, "Counter-Strike 2")
   */
  synonyms?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    focusKeyword?: string | null;
    noindex?: boolean | null;
  };
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?: (ContentBlock | FaqBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    focusKeyword?: string | null;
    noindex?: boolean | null;
  };
  /**
   * Lotin, ikkala yozuvda bir xil. Bo'sh qoldirilsa sarlavhadan yasaladi.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  richText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null)
      | ({
          relationTo: 'tags';
          value: number | Tag;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'feed.poll' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'scrapeItem' | null;
  taskSlug?: ('inline' | 'feed.poll' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'scraped-items';
        value: number | ScrapedItem;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        name?: T;
        url?: T;
        scrapedItem?: T;
        id?: T;
      };
  relatedPosts?: T;
  notesForEditor?: T;
  reviewNotes?:
    | T
    | {
        user?: T;
        createdAt?: T;
        note?: T;
        id?: T;
      };
  rejectReason?: T;
  telegram?:
    | T
    | {
        script?: T;
        messageId?: T;
        sentAt?: T;
        error?: T;
        id?: T;
      };
  cyrlLocked?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        noindex?: T;
      };
  slug?: T;
  workflowStatus?: T;
  category?: T;
  tags?: T;
  authors?: T;
  assignee?: T;
  lockedUntil?: T;
  publishedAt?: T;
  scheduledAt?: T;
  rewrittenBy?: T;
  aiDisclosure?: T;
  isFeatured?: T;
  isBreaking?: T;
  telegramSkip?: T;
  cyrlStale?: T;
  readingTime?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        noindex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        noindex?: T;
      };
  slug?: T;
  color?: T;
  order?: T;
  isInMenu?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  synonyms?:
    | T
    | {
        value?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        noindex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  position?: T;
  bio?: T;
  avatar?: T;
  user?: T;
  isActive?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  license?: T;
  licenseUrl?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  homepageUrl?: T;
  feeds?:
    | T
    | {
        url?: T;
        feedCategory?: T;
        mapsTo?: T;
        isActive?: T;
        lastPolledAt?: T;
        lastStatus?: T;
        lastNewItems?: T;
        etag?: T;
        lastModified?: T;
        lastError?: T;
        id?: T;
      };
  language?: T;
  fetchMode?: T;
  priority?: T;
  pollIntervalMin?: T;
  rateLimitSec?: T;
  selectors?: T;
  keywordRules?:
    | T
    | {
        keyword?: T;
        category?: T;
        boost?: T;
        id?: T;
      };
  tosNotes?: T;
  isActive?: T;
  robotsCheckedAt?: T;
  lastRequestAt?: T;
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraped-items_select".
 */
export interface ScrapedItemsSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  status?: T;
  url?: T;
  canonicalUrl?: T;
  urlHash?: T;
  author?: T;
  publishedAt?: T;
  language?: T;
  excerpt?: T;
  extractedText?: T;
  imageUrls?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  sourceTags?: T;
  contentHash?: T;
  clusterId?: T;
  rawHtmlKey?: T;
  cleanHtmlKey?: T;
  fetchMeta?: T;
  error?: T;
  score?: T;
  wordCount?: T;
  suggestedCategory?: T;
  post?: T;
  rejectReason?: T;
  handledBy?: T;
  handledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  defaultOgImage?: (number | null) | Media;
  socials?:
    | {
        platform: 'telegram_latn' | 'telegram_cyrl' | 'instagram' | 'youtube' | 'x' | 'facebook' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  analytics?: {
    ga4MeasurementId?: string | null;
    yandexMetrikaId?: string | null;
    googleSiteVerification?: string | null;
    yandexVerification?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        type: 'category' | 'page' | 'custom';
        category?: (number | null) | Category;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  moreItems?:
    | {
        label: string;
        type: 'category' | 'page' | 'custom';
        category?: (number | null) | Category;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title?: string | null;
        links?:
          | {
              label: string;
              type: 'category' | 'page' | 'custom';
              category?: (number | null) | Category;
              page?: (number | null) | Page;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telegram-settings".
 */
export interface TelegramSetting {
  id: number;
  channels?:
    | {
        script: 'uz-Latn' | 'uz-Cyrl';
        chatId: string;
        isEnabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * O'rinbosarlar: {{title}}, {{excerpt}}, {{url}}, {{hashtags}}. Caption ≤ 1024 belgi.
   */
  template?: string | null;
  hashtagsCount?: number | null;
  alertChatId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraping-settings".
 */
export interface ScrapingSetting {
  id: number;
  isEnabled?: boolean | null;
  minScore?: number | null;
  jobsBatchLimit?: number | null;
  jobsDeadlineSec?: number | null;
  maxNewItemsPerPoll?: number | null;
  defaultPollIntervalMin?: number | null;
  /**
   * Feed’dagi bundan eski yozuvlar olinmaydi
   */
  maxItemAgeHours?: number | null;
  extractedTextRetentionDays?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  logoDark?: T;
  defaultOgImage?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        ga4MeasurementId?: T;
        yandexMetrikaId?: T;
        googleSiteVerification?: T;
        yandexVerification?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        category?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  moreItems?:
    | T
    | {
        label?: T;
        type?: T;
        category?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              category?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telegram-settings_select".
 */
export interface TelegramSettingsSelect<T extends boolean = true> {
  channels?:
    | T
    | {
        script?: T;
        chatId?: T;
        isEnabled?: T;
        id?: T;
      };
  template?: T;
  hashtagsCount?: T;
  alertChatId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraping-settings_select".
 */
export interface ScrapingSettingsSelect<T extends boolean = true> {
  isEnabled?: T;
  minScore?: T;
  jobsBatchLimit?: T;
  jobsDeadlineSec?: T;
  maxNewItemsPerPoll?: T;
  defaultPollIntervalMin?: T;
  maxItemAgeHours?: T;
  extractedTextRetentionDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFeedPoll".
 */
export interface TaskFeedPoll {
  input: {
    sourceId: number;
  };
  output: {
    polledFeeds?: number | null;
    notModified?: number | null;
    failedFeeds?: number | null;
    newItems?: number | null;
    duplicates?: number | null;
    skippedOld?: number | null;
    deferredFeeds?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowScrapeItem".
 */
export interface WorkflowScrapeItem {
  input: {
    scrapedItemId: number;
    /**
     * RSS’dagi matn (rss_only manbalar uchun extract shu matndan)
     */
    contentHtml?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}